/** Exact owner-supplied regression corpus; intentionally retain misspellings. */
export const realFoodCorpus = [
  "1 bowl kher",
  "1 aloo pyaaz paratha, 1 plate french fry, 1 glass sweet lassai",
  "5 mediums size idli, half small bowl sambar, 2 potato wedges, one small cold coffee, one big spoon boiled corn, one muffin",
  "1 medium margarita pizza and 1 glass oreo milkshake",
  "26.5 gram green uncle chips",
  "180 ml sprite",
  "30 gram masala chips",
  "180 ml fanta can",
  "1 small bowl Chocos, one small glass butterscotch milkshake, 3 medium sized idli and one small bowl sambar, one big spoon poha.",
  "1 Sweet lassai",
  "2 aloo pyaaz paratha",
  "1 bowl Chocos cereal",
  "2 samosa and 1 plate rajma chawal",
  "2 plate rajma chawal",
  "30 g Chocos + 200 ml milk",
  "1 apple",
  "30cm paneer tikka subway sandwich, subway crispers, cornitos small bag, subway dou choc cookie",
  "2 pieces kaju katli, 2 plate maggie and 10 peices of jimmy jam",
  "1 glass rooh afza milk and 10 peice bread toast",
  "Jimmy jam",
  "1 plate khichdi",
  "Dairy milk 26 rupees",
  "Half Orange",
  "1 half plate vegetable biryani and 3 peice of kaju katli",
  "3 roti and 1 bowl paneer curry",
] as const;
