export type FoodType = "INGREDIENT" | "GENERIC_FOOD" | "INDIAN_PREPARED_DISH" | "PACKAGED_PRODUCT" | "RESTAURANT_ITEM" | "RECIPE" | "USER_CUSTOM";
export type Confidence = "exact" | "high" | "medium" | "low" | "unknown";
export type Basis = "g" | "ml" | "serving";
export type Nutrition = { kcal: number; protein: number; carbs: number; fat: number; fiber: number | null; sugar: number | null; sodium: number | null };
export type Source = { id: string; name: string; version: string; url: string; license: string; licenseUrl: string;
  retrieved: string; transformation: string; recordsImported: number; sha256: string; rawBytes: number };
export type Food = { id: string; canonicalName: string; normalizedName: string; foodType: FoodType; source: string; sourceId: string;
  locale: string; category: string; description: string; basis: Basis; nutrition: Nutrition | null; defaultPortion: string | null;
  brand?: string; restaurant?: string; variant?: string; barcode?: string; packageQuantity?: string; servingDescription?: string;
  countries?: string[]; density?: { gramsPerMl: number; source: string }; note?: string };
export type Portion = { id: string; foodId: string; unit: string; size: string | null; amount: number; basis: Basis;
  source: string; confidence: Confidence; description: string };
export type Alias = { name: string; foodId: string; priority: number; source: string; locale: string };
export type Recipe = { id: string; foodId: string; version: number; yieldGrams: number; servings: number;
  ingredients: { foodId: string; amount: number; basis: Basis; preparation: string }[]; note: string };
export type Catalog = { version: string; sources: Source[]; foods: Food[]; aliases: Alias[]; portions: Portion[]; recipes: Recipe[] };
export type ParsedItem = { rawText: string; normalizedText: string; food: string; quantity: number; explicitQuantity: boolean;
  unit: string | null; size: string | null; variant: string | null; modifiers: string[]; price: boolean; error?: string };
export type Candidate = { foodId: string; name: string; source: string; score: number };
export type Resolution = { parsed: ParsedItem; canonicalFoodId: string | null; canonicalName: string | null;
  status: "resolved" | "clarification"; confidence: Confidence; method: string; candidates: Candidate[];
  portion: { amount: number; basis: Basis; source: string; description: string } | null;
  nutrition: Nutrition | null; per100: Nutrition | null; source: { dataset: string; id: string; version: string; license: string } | null;
  warnings: string[]; recipe: Recipe | null };
export type Estimate = { rawText: string; databaseVersion: string; userVersion: number; items: Resolution[];
  totals: Nutrition | null; incomplete: boolean };
export type Mapping = { phrase: string; foodId: string; amount: number | null; basis: Basis; unit: string | null };
export type UserData = { schemaVersion: 1; revision: number; foods: Food[]; aliases: Alias[]; portions: Portion[]; recipes: Recipe[]; mappings: Mapping[] };
export const emptyUserData = (): UserData => ({ schemaVersion: 1, revision: 0, foods: [], aliases: [], portions: [], recipes: [], mappings: [] });
