import { writeFileSync } from "node:fs";
import { createNutritionEngine } from "../src/lib/nutrition/runtime";
import { realFoodCorpus } from "../src/lib/nutrition/corpus";

globalThis.fetch = async () => { throw new Error("No network during corpus report"); };
const engine = createNutritionEngine();
const reports = realFoodCorpus.map((text) => engine.estimate(text));
const number = (value: number) => value.toFixed(2).replace(/\.?0+$/, "");
let report = `# Real input interpretations\n\nGenerated by \`npm run food:corpus\` with networking blocked. Database ${engine.catalog.data.version}. Nutrients below use display rounding only; engine output retains full precision. Recipes and assumed household portions require review.\n\n`;
for (const result of reports) {
  report += `## ${result.rawText}\n\n| Parsed food / quantity | Local record | Portion | Source | Confidence / method | kcal · P · C · F (g) |\n|---|---|---|---|---|---|\n`;
  for (const item of result.items) {
    report += `| ${item.parsed.food} / ${item.parsed.quantity} ${item.parsed.size ?? ""} ${item.parsed.unit ?? "default"}${item.parsed.variant ? `; ${item.parsed.variant}` : ""} | ${item.canonicalFoodId ?? "unresolved"} | ${item.portion ? `${number(item.portion.amount)} ${item.portion.basis}` : "clarify"} | ${item.source?.dataset ?? "—"} | ${item.confidence} / ${item.method} | ${item.nutrition ? [item.nutrition.kcal, item.nutrition.protein, item.nutrition.carbs, item.nutrition.fat].map(number).join(" · ") : "unavailable"} |\n`;
  }
  if (result.incomplete) report += "\nIncomplete: select a product/portion or teach a food. No complete meal total is emitted.\n";
  report += "\n";
}
writeFileSync("docs/nutrition-corpus.md", report.trimEnd() + "\n");
console.log(`Documented ${reports.length} exact owner examples.`);
